// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: job_location.proto

package job_location

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobCityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityId int32 `protobuf:"varint,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
}

func (x *GetJobCityRequest) Reset() {
	*x = GetJobCityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_location_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobCityRequest) ProtoMessage() {}

func (x *GetJobCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_location_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobCityRequest.ProtoReflect.Descriptor instead.
func (*GetJobCityRequest) Descriptor() ([]byte, []int) {
	return file_job_location_proto_rawDescGZIP(), []int{0}
}

func (x *GetJobCityRequest) GetCityId() int32 {
	if x != nil {
		return x.CityId
	}
	return 0
}

type GetJobStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateId int32 `protobuf:"varint,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
}

func (x *GetJobStateRequest) Reset() {
	*x = GetJobStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_location_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStateRequest) ProtoMessage() {}

func (x *GetJobStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_location_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStateRequest.ProtoReflect.Descriptor instead.
func (*GetJobStateRequest) Descriptor() ([]byte, []int) {
	return file_job_location_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobStateRequest) GetStateId() int32 {
	if x != nil {
		return x.StateId
	}
	return 0
}

type GetJobLocationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobIds []int32 `protobuf:"varint,1,rep,packed,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"`
}

func (x *GetJobLocationsRequest) Reset() {
	*x = GetJobLocationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_location_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobLocationsRequest) ProtoMessage() {}

func (x *GetJobLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_location_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobLocationsRequest.ProtoReflect.Descriptor instead.
func (*GetJobLocationsRequest) Descriptor() ([]byte, []int) {
	return file_job_location_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobLocationsRequest) GetJobIds() []int32 {
	if x != nil {
		return x.JobIds
	}
	return nil
}

type GetJobCityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityId int32  `protobuf:"varint,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	City   string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *GetJobCityResponse) Reset() {
	*x = GetJobCityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_location_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobCityResponse) ProtoMessage() {}

func (x *GetJobCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_location_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobCityResponse.ProtoReflect.Descriptor instead.
func (*GetJobCityResponse) Descriptor() ([]byte, []int) {
	return file_job_location_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobCityResponse) GetCityId() int32 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *GetJobCityResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetJobStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateId int32  `protobuf:"varint,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	State   string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *GetJobStateResponse) Reset() {
	*x = GetJobStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_location_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStateResponse) ProtoMessage() {}

func (x *GetJobStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_location_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStateResponse.ProtoReflect.Descriptor instead.
func (*GetJobStateResponse) Descriptor() ([]byte, []int) {
	return file_job_location_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobStateResponse) GetStateId() int32 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *GetJobStateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type SingleJobLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId   int32  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CityId  int32  `protobuf:"varint,2,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	City    string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	StateId int32  `protobuf:"varint,4,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	State   string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *SingleJobLocationResponse) Reset() {
	*x = SingleJobLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_location_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleJobLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleJobLocationResponse) ProtoMessage() {}

func (x *SingleJobLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_location_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleJobLocationResponse.ProtoReflect.Descriptor instead.
func (*SingleJobLocationResponse) Descriptor() ([]byte, []int) {
	return file_job_location_proto_rawDescGZIP(), []int{5}
}

func (x *SingleJobLocationResponse) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *SingleJobLocationResponse) GetCityId() int32 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *SingleJobLocationResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *SingleJobLocationResponse) GetStateId() int32 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *SingleJobLocationResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GetJobLocationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobLocations []*SingleJobLocationResponse `protobuf:"bytes,1,rep,name=job_locations,json=jobLocations,proto3" json:"job_locations,omitempty"`
}

func (x *GetJobLocationsResponse) Reset() {
	*x = GetJobLocationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_location_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJobLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobLocationsResponse) ProtoMessage() {}

func (x *GetJobLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_location_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobLocationsResponse.ProtoReflect.Descriptor instead.
func (*GetJobLocationsResponse) Descriptor() ([]byte, []int) {
	return file_job_location_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobLocationsResponse) GetJobLocations() []*SingleJobLocationResponse {
	if x != nil {
		return x.JobLocations
	}
	return nil
}

var File_job_location_proto protoreflect.FileDescriptor

var file_job_location_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6a, 0x6f, 0x62, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6a, 0x6f, 0x62, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x43, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x69, 0x74, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64,
	0x22, 0x2f, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49,
	0x64, 0x22, 0x31, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6a,
	0x6f, 0x62, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x6a, 0x6f,
	0x62, 0x49, 0x64, 0x73, 0x22, 0x41, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x43, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x69,
	0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x22, 0x46, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4a, 0x6f,
	0x62, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x90, 0x01, 0x0a, 0x19, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a,
	0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6a,
	0x6f, 0x62, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x67, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a,
	0x0d, 0x6a, 0x6f, 0x62, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x6a,
	0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x9f, 0x02, 0x0a, 0x12,
	0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x51, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x43, 0x69, 0x74, 0x79,
	0x12, 0x1f, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24,
	0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65,
	0x74, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x38, 0x5a,
	0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x65, 0x61, 0x6e,
	0x6d, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x69, 0x2f, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x2d, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6a, 0x6f, 0x62, 0x5f, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_job_location_proto_rawDescOnce sync.Once
	file_job_location_proto_rawDescData = file_job_location_proto_rawDesc
)

func file_job_location_proto_rawDescGZIP() []byte {
	file_job_location_proto_rawDescOnce.Do(func() {
		file_job_location_proto_rawDescData = protoimpl.X.CompressGZIP(file_job_location_proto_rawDescData)
	})
	return file_job_location_proto_rawDescData
}

var file_job_location_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_job_location_proto_goTypes = []interface{}{
	(*GetJobCityRequest)(nil),         // 0: job_location.GetJobCityRequest
	(*GetJobStateRequest)(nil),        // 1: job_location.GetJobStateRequest
	(*GetJobLocationsRequest)(nil),    // 2: job_location.GetJobLocationsRequest
	(*GetJobCityResponse)(nil),        // 3: job_location.GetJobCityResponse
	(*GetJobStateResponse)(nil),       // 4: job_location.GetJobStateResponse
	(*SingleJobLocationResponse)(nil), // 5: job_location.SingleJobLocationResponse
	(*GetJobLocationsResponse)(nil),   // 6: job_location.GetJobLocationsResponse
}
var file_job_location_proto_depIdxs = []int32{
	5, // 0: job_location.GetJobLocationsResponse.job_locations:type_name -> job_location.SingleJobLocationResponse
	0, // 1: job_location.JobLocationService.GetJobCity:input_type -> job_location.GetJobCityRequest
	1, // 2: job_location.JobLocationService.GetJobState:input_type -> job_location.GetJobStateRequest
	2, // 3: job_location.JobLocationService.GetJobLocations:input_type -> job_location.GetJobLocationsRequest
	3, // 4: job_location.JobLocationService.GetJobCity:output_type -> job_location.GetJobCityResponse
	4, // 5: job_location.JobLocationService.GetJobState:output_type -> job_location.GetJobStateResponse
	6, // 6: job_location.JobLocationService.GetJobLocations:output_type -> job_location.GetJobLocationsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_job_location_proto_init() }
func file_job_location_proto_init() {
	if File_job_location_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_job_location_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobCityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_location_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_location_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobLocationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_location_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobCityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_location_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_location_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleJobLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_location_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJobLocationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_job_location_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_location_proto_goTypes,
		DependencyIndexes: file_job_location_proto_depIdxs,
		MessageInfos:      file_job_location_proto_msgTypes,
	}.Build()
	File_job_location_proto = out.File
	file_job_location_proto_rawDesc = nil
	file_job_location_proto_goTypes = nil
	file_job_location_proto_depIdxs = nil
}
