version: '3'
services:
  web:
    build:
      context: .docker/web
      dockerfile: Dockerfile
    working_dir: /web
    volumes:
      - ./web:/web
      - /web/node_modules/
    ports:
      - "8080:8080"

  job-http:
    build:
      context: .docker/app
    volumes:
      - ./src:/src
    working_dir: /src/job
    ports:
      - "127.0.0.1:3000:$PORT"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http

  job-grpc:
    build:
      context: .docker/app
    volumes:
      - ./src:/src
    working_dir: /src/job
    ports:
      - "127.0.0.1:3001:$PORT"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: grpc