version: '3'
services:

  job-http:
    build:
      context: .docker/app
    volumes:
      - ./src:/src
    working_dir: /src/job
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http
    networks:
      - jobnet

  job-grpc:
    build:
      context: .docker/app
    volumes:
      - ./src:/src
    working_dir: /src/job
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: grpc
    networks:
      - jobnet

  job-location-grpc:
    build:
      context: .docker/app
    volumes:
      - ./src:/src
    working_dir: /src/job-location
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: grpc
    networks:
      - jobnet

  jobs-db:
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - 33060:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - jobnet

networks:
  jobnet:
    driver: bridge